### ISSUE TITLE
Option instance-name not preserved if OLA already running

### ISSUE THREAD

**Issue by DaAwesomeP** [OpenLightingProject/ola#1856] opened 2023-04-25 15:20 UTC
I found a small bug with `instance-name` in `ola-server.conf` while automating system configuration.

- If you edit the `instance-name` while OLA is running, then it will overwrite `instance-name` when OLA next restarts to what it was when OLA first started.
- If you edit `instance-name` while OLA is not running, then OLA will adopt the change when it starts next.

I haven't tried to reproduce this yet on multiple systems, but I think I have experienced it once before. This doesn't appear to apply to the `ola-kinet.conf`, `ola-port.conf`, or `ola-universe.conf` files that I am also editing.

**Comment by peternewman** [comment] 2023-04-26 15:07
Duplicate of #125 .

See also https://www.openlighting.org/ola/get-help/ola-faq/#Why_aren8217t_my_settings_saved_when_I_disconnect_power_from_the_Raspberry_Pi

I'm a bit confused why you don't see it with everything @DaAwesomeP , unless you're adding new entries in the other cases which I guess may survive, whereas the old instance-name will still exist to be overwritten. If you started OLA with a particular port patched to universe 1, then changed it to 2 in the patch I assume you'd see the same overwriting behaviour too.

**Closed by peternewman** 2023-04-26 15:07 UTC

**Comment by DaAwesomeP** [comment] 2023-04-26 15:23
> I'm a bit confused why you don't see it with everything @DaAwesomeP , unless you're adding new entries in the other cases which I guess may survive, whereas the old instance-name will still exist to be overwritten.

I think this is it exactly. I am only adding new entries in the other cases.
