### ISSUE TITLE
Occasional hangs when doing full discovery via the ENTTEC USBDMX Pro

### ISSUE THREAD

**Issue by felicitus** [OpenLightingProject/ola#341] opened 2014-02-19 15:14 UTC
Hi,

I get occasional hangs when doing full discovery via the ENTTEC USBDMX Pro. The log shows the following:

user.info: Feb 19 16:00:38 olad: EnttecUsbProWidget.cpp:280: Full discovery triggered
user.info: Feb 19 16:00:38 olad: EnttecUsbProWidget.cpp:324: Un-muting all devices
user.info: Feb 19 16:00:38 olad: EnttecUsbProWidget.cpp:343: Sending DUB packet: 0000:00000000 - ffff:ffffffff

After that, it hangs forever. I see several "break too short" messages using the logic sniffer. I need to restart the OLA daemon in order to use OLA again. The issue _might_ be caused by noise on the line or a timing issue with one of my RDM responders, however, OLA should handle this gracefully and not simply hang forever.

**Comment by alvangee** [comment] 2015-03-24 14:55
Just updated to version 0.9.5 from git and got ENTTEC DMX USB PRO Mk2 hanging. It happens not only on Full Discovery, but occasionally when requesting parameters in Web UI. Couldn't run RDM tests as it hangs at the very first one.
Before upgrading to 0.9.5 everything was working fine, including RDM tests.
I use VMWare on Win8 64bit
Is there a way to downgrade back to 0.9.4 or resolve this issue in 0.9.5?

**Comment by nomis52** [comment] 2015-03-25 02:57
@alvangee do you have the logs ? Please run with debug mode (-l 4) .

**Comment by alvangee** [comment] 2015-03-25 07:58
@nomis52 Well, sorry for bothering. Looks like it was problem in the bus so controller was thinking there's a collision, thus constantly trying to get correct response hanging in Discovery forever.
Now it works fine, including RDM tests.

**Comment by nomis52** [comment] 2015-03-25 15:33
Can you reproduce it at all? I'm convinced we have a bug here so we need to understand it to get it fixed.

Simon

**Comment by alvangee** [comment] 2015-03-25 19:59
I'll try to get it hanging again. BTW, not very familiar with Linux and it's file system and all that. After running OLA with -l 4 where do I get log file? And should I show it here or send it via e-mail to you?

**Comment by peternewman** [comment] 2015-03-26 00:32
Isn't this similar to the problems Arjan was having when we wasn't returning replies as the Enttec unit?

**Comment by nomis52** [comment] 2015-03-26 03:15
@alvangee : if you're running the git version, you can do:

olad -l 3 2>&1 | tee /tmp/olad.log

That will log the /tmp/olad.log as well as printing everything on the screen. Once you've triggered the issue you can use Control-C to stop olad. The log file will be in /tmp/olad.log, you can either upload it somewhere and paste the link or email it to me directly. 

If you have questions jump into the IRC chat room and there should be someone around to help you.

**Comment by alvangee** [comment] 2015-03-26 07:48
Apparently, very easy way to hang PRO Mk2 in Discovery is to connect responders' RS485 A+ and B- lines together. Our responder has two parallel RS485 inputs which are connected, so you can have multiple devices on a bus. Now, I connect one pair of inputs to PRO Mk2, connect two wires to another pair of inputs and when this wires touch each other - here we go.

The log here shows first succesful Discovery, when lines were not in contact, then I connect them and run Discovery again - this time it hangs forever. If I disconnect RS485 lines during this hanging it's no use, OLA stays in Discovery until you stop OLA with Control-C or close terminal.

Here's the log: http://paste.debian.net/163301

**Comment by nightrune** [comment] 2015-03-26 16:00
@alvangee Can you make a quick sketch of the wiring in the system?

**Comment by nomis52** [comment] 2015-03-26 16:05
This is very helpful thanks, it's really starting to sound like a bug in the Enttec unit.

Can you capture what's happening on the RS485 line? Do you have a logic analyser ?

I've pushed an update to my repo: https://github.com/nomis52/ola.git which adds logging for received messages. Do you mind building that and running the failure case again, possibly with the logic capture.

**Comment by nomis52** [comment] 2015-03-26 16:08
The change is in the main repo now.

**Comment by alvangee** [comment] 2015-03-26 17:53
I don't have a logic analyser, but I have two Pro Mk2s, so could use the second with Enttec RDM Sniffer - maybe this will show something.
Due to time zones difference (I'm in Moscow, Russia), I'll be able to do this only tomorrow, in about 14-15 hours from now.
I'll provide a sketch of wiring too.

**Comment by nomis52** [comment] 2015-03-27 02:27
Thanks. Once I can reproduce it we can file a bug report with Enttec.

**Comment by alvangee** [comment] 2015-03-27 08:53
Here we go.
I connected two Enttec Mk2 to responder, one used with OLA, second was used with RDM Sniffer.
Log of OLA: http://paste.debian.net/163467
Log of Sniffer: http://paste.debian.net/163469

Looks like Mk2 just stops sending anything on bus, as there's nothing in Sniffer log and the LED on Mk2 doesn't blink Green (as it does when there's something on DMX line 1).

Now, how to reproduce this. Here's the PCB of our Responder:
![responder_pcb](https://cloud.githubusercontent.com/assets/5708802/6864613/1d9f3c18-d475-11e4-8327-7ec584f57315.jpg)
You can see X3 and X4 are RS485 lines. This time I connected one Mk2 to X3 (this one works with OLA) and another Mk2 to X4 (this one works with Sniffer). Then I start OLA and it finds Mk2, creates a Universe, runs Discovery and finds the Responder. Then I request some parameters and run full Discovery couple more times just to show it works fine.
Then I connect X3's RS+ and RS- lines (simply short them), run Discovery and it hangs with nothing going from Mk2's lines. Disconnecting RS+ and RS- doesn't help, the OLA just hangs in Discovery forever. Pressing ESC button doesn't help either - even if it stops showing message "RDM Discovery running", the OLA can't refresh any of the parameters or run Discovery again - it shows this message again until ESC is pressed. The only way to get OLA working is to press Ctrl+C to stop it and then restart it. On CTRL+C this message shows up:
![image](https://cloud.githubusercontent.com/assets/5708802/6864780/0ed89222-d477-11e4-9da4-bca4998b2989.png)

All our responders have double RS485 lines, so I can't check if this happens with single RS input if you short it's RS+ and RS- lines, but it probably will. 

Hell, I hope you understand my English and how I got it hanging :) If you have any questions, please ask.

**Comment by nomis52** [comment] 2015-03-27 14:56
Thanks, we're getting closer.

Can you run another test for me? Please pull in the changes from https://github.com/nomis52/ola.git which adds transaction number logging.

Then can you set it up as follows:

Mk2 (OLA) -----> Mk2 (sniffer ) -------> X3

Then do what you did before, run discovery, short X3 and run discovery again.

I don't have a Mk2 but I'll try to reproduce this with the USB Pro tonight.

**Comment by alvangee** [comment] 2015-03-27 15:07
Sorry, we need to take a break for weekend. I'm off the work already.
I'll run this test on Monday (after 10 am Moscow time).

**Comment by nomis52** [comment] 2015-03-27 15:08
That's fine. No rush.

**Comment by alvangee** [comment] 2015-04-02 14:48
Sorry it took so long, second Mk2 was busy with another project.

I must say I'm not very good at using git in Linux via command line. I only used it on Win with GUI before.

On VMware's Ubuntu I use this procedure from tutorial to update OLA:
  git pull
  autoreconf -i
  ./configure --enable-python-libs
  make
  make check
  sudo make install

So I tried to pull using "git pull https://github.com/nomis52/ola.git", but then I was asked about merging, commiting and and told that I need to write commit message. As I wasn't sure what exactly I was doing, I decided to just cancel it.

So please, if you still need me to run this test using that special version of OLA, please tell me how to pull it and not to ruin anything.

Anyway, I tied two Mk2s as you said (that's different order from what I used before) and here's logs.
OLA log: http://paste.debian.net/164491
Sniffer log: http://paste.debian.net/164496

There're transaction numbers in sniffer log.

**Comment by nomis52** [comment] 2015-04-02 16:30
It would have been safe to merge.

In any case, the changes are now in the mainline so you can just run 'git pull' to pick them up.

**Comment by nomis52** [comment] 2015-04-02 16:30
No worries, it would have been safe to merge but it's good to be cautious.

**Comment by alvangee** [comment] 2015-04-03 13:51
Done.
Here's OLA log: http://paste.debian.net/164688
Here's Sniffer log: http://paste.debian.net/164691
I did several normal Discoveries, then the last one was with shorted X3's RS+ and RS-.

One more thing. In Sniffer log you can see two last messages have RDM Errors Packet Type. It's not seen in log, but in Sniffer window this messages also had "bad timing" marks and unusual duration.
I run the test three more times and always, when I short X3, this messages of last hung Discovery are similar - bad timing and long duration. I did the screenshot of last of my tests - it's not the same I got the logs with, but shows exactly the same thing:
![sniffer_window](https://cloud.githubusercontent.com/assets/5708802/6983012/79abbe44-da21-11e4-8b28-839b10f5dc84.jpg)

**Comment by nomis52** [comment] 2015-04-03 15:55
alvangee: do you want to drop me an email so I have your address and then I can cc you on the thread with Enttec.

I can't reproduce this with my USB Pro (Mk1) so I suspect it's a Mk2 issue.

In the meantime I'll see if we can work around it in OLA.

**Comment by alvangee** [comment] 2015-04-03 17:12
I made my email visible.

**Comment by nomis52** [comment] 2015-04-04 15:28
Thanks, I've started a thread with Enttec (you're cc'ed) and have https://github.com/OpenLightingProject/ola/pull/697 which tries to detect the dropped response. Once that change is merged, can you rebuild and see if you get a "Enttec watchdog fired" message in the logs.

**Comment by alvangee** [comment] 2015-04-06 08:36
No, there's no "Enttec watchdog fired" message: http://paste.debian.net/165199

**Comment by roelofsw** [comment] 2015-10-06 01:17
Greetings,
I've stumbled onto this thread while playing with Ja-Rule and the same Enttec unit, and getting watchdog fired errors.  Has there been any resolution from Enttec on this issue?
Kind regards,

**Comment by nomis52** [comment] 2015-10-07 02:00
No, no response. I'm going to try to get access to a MK2 unit so I can reproduce the issue.

**Comment by nomis52** [comment] 2015-10-25 15:48
I've got hold of an MK2 unit, now I'm just trying to reproduce the failure.

**Comment by nomis52** [comment] 2015-10-25 16:46
Confirmed with firmware 4.10. I'll chat to Enttec today and see if we can work around it in OLA.

**Closed** 2015-10-26 16:50 UTC
Labels: bug, Component-Plugin
