### ISSUE TITLE
Build issues with protobuf 3.11

### ISSUE THREAD

**Issue by yoe** [OpenLightingProject/ola#1634] opened 2020-04-27 07:11 UTC
Trying to build ola on Debian unstable, I get errors related to protobuf, like so:

    common/protocol/OlaService.pb.cpp:37:29: error: expected constructor, destructor, or type conversion before '(' token
        37 | GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);

For an example failing build, see https://salsa.debian.org/wouter/ola/-/jobs/699377

Not sure whether this is a bug in the Debian packaging of protobuf (GOOGLE_PROTOBUF_DECLARE_ONCE is declared in some "stub" header in the libprotobuf-dev package that doesn't seem to be included by the generated code), or whether it's the result of an API change. If the former, please just let me know and close this bug.

Thanks,

**Comment by peternewman** [comment] 2020-04-27 08:07
> Trying to build ola on Debian unstable, I get errors related to protobuf, like so:
> 
> ```
> common/protocol/OlaService.pb.cpp:37:29: error: expected constructor, destructor, or type conversion before '(' token
>     37 | GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
> ```

I'm going to close this as a duplicate of #1550 , which was initially about a Protobuf 3.7 error, but then @kripton found that bug appeared with Protobuf 3.11: https://github.com/OpenLightingProject/ola/issues/1550#issuecomment-599145993
 
The good news is it's already fixed in master in #1620 and will be in 0.10 shortly via #1630 thanks to @kripton and others.

> Not sure whether this is a bug in the Debian packaging of protobuf (GOOGLE_PROTOBUF_DECLARE_ONCE is declared in some "stub" header in the libprotobuf-dev package that doesn't seem to be included by the generated code), or whether it's the result of an API change. If the former, please just let me know and close this bug.

They have indeed changed the API, so it seems a bit odd the declare still exists somewhere in libprotobuf-dev, whereabouts is that?

**Closed** 2020-04-27 08:07 UTC
Labels: Language-C++, Maintainability, OpSys-Linux, bug
