### ISSUE TITLE
Python version check bug

### ISSUE THREAD

**Issue by JamCam** [OpenLightingProject/ola#1780] opened 2022-05-25 14:06 UTC
Hi

Your python version check in OlaClient.py fails on Python 3.10

line 957
if sys.version >= '3.2':
  request.data = data.tobytes()
else:
  request.data = data.tostring()

The best solution I can see, others may have a better solution, is

pv = platform.python_version_tuple()
if int(pv[0]) >= 3 and int(pv[1]) > 2:
  request.data = data.tobytes()
else:
  request.data = data.tostring()

**Comment by peternewman** [comment] 2022-05-26 00:29
Hi @JamCam ,

This has already been fixed:
https://github.com/OpenLightingProject/ola/blob/e95de59a04c79ddd6ba745578e4183301f4b98b7/python/ola/OlaClient.py#L955

See #1757 .

You might need to run from source if you're doing stuff with Python 3, although unfortunately even there, there are a few outstanding issues. Some (but not all) are sorted in #1761 .

**Comment by peternewman** [comment] 2022-11-19 18:37
Did that work for you @JamCam ?

Let us know if you see any other Python 3 related bugs during your usage of it.

**Comment by peternewman** [comment] 2023-02-15 03:18
I'll close this as it's a duplicate of #1755 and was fixed in #1757 .

**Closed by peternewman** 2023-02-15 03:18 UTC
Labels: question, Maintainability, API-Python, Language-Python
